name: Flutter CI

on:
  push:
    branches:
      - master
      - flutterRefactor
  pull_request:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: 'latest'
        channel: 'stable'

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: 'latest'
        channel: 'stable'
    - name: Build APK
      run: |
        cd ./client/omo_client
        flutter build apk

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: 'latest'
        channel: 'stable'
    - name: Run Flutter tests
      run: |
        cd ./client/omo_client
        flutter test
